name             'sbp_cloudmonkey'
maintainer       'Schuberg Philis'
maintainer_email 'cookbooks@schubergphilis.com'
chef_version     '>= 14'
license          'Apache-2.0'
description      'Installs/Configures cloudmonkey'
issues_url       'https://github.com/sbp-cookbooks/sbp_cloudmonkey/issues'
source_url       'https://github.com/sbp-cookbooks/sbp_cloudmonkey'
version          '0.2.0'

supports 'centos'
supports 'debian'
supports 'redhat'
supports 'ubuntu'
